### ISSUE TITLE
Allow revocation of guarantor

### ISSUE THREAD

**Issue by SmallPatatas** [Fediseer/fediseer#24]
New instances can solicit a guarantee and receive it from an unknown/untrusted instance.

 So, a method to revoke, and then either resolicit, or ask a specific entity for a guarantee, seems potentially useful. Especially at the early adoption stage where these decisions may have larger future consequences.

**Comment by db0** [comment]
You can already revoke your own guarantee, or revoke the guarantee from someone you guaranteed for. Simply use DELETE on `/api/v1/guarantee` and pass you own API key and domain.

I'll have to check if the GUI supports this functionality

**Comment by SmallPatatas** [comment]
Added as a GUI issue - thanks!
