### ISSUE TITLE
Allow admins to opt-out

### ISSUE THREAD

**Issue by jepyang** [Fediseer/fediseer#48]
As of right now, fediseer is, itself, functionally a bad actor.

Yes, an opt-out option could mitigate the effectiveness of the system. No, that is not a good reason to disallow opt-outs. Removing people’s agency and asserting your own authority over them is not a solution to abuse, it *is* abuse. It’s malicious.

**Comment by db0** [comment]
This goes against the purpose of the system. If this was possible, the target of any problem site, including CSAM and neonazi instances could simply opt-out to avoid notice. 

Furthermore, this request is unreasonable. There's plenty of other sites such as thebadspace, the oliphant, fedinuke lists etc who display similar lists. having review sites like this is partly how the fediverse has always worked.
