### ISSUE TITLE
DM from instance claim never arrived, can't request again

### ISSUE THREAD

**Issue by tux93** [Fediseer/fediseer#69]
I recently tried to claim my (GoToSocial) instance via gui.fediseer.com, and like in [this earlier Lemmy post](https://lemmy.dbzer0.com/post/5046849) the DM from the botsin.space account never arrived.

Neither botsin.space nor the account were blocked at the time of claiming, but in the meantime I followed the account. It would be great if you could reset / resend the API key, thanks!

Admin account: `@flann@boosts.squirrel.pictures`

**Comment by db0** [comment]
I sent you first without a proxy account, did you get a PM from fediseer.com
?

**Comment by tux93** [comment]
I did not, I did receive a DM from the botsin.space account now though; thank you!
